FROM python:3.10-slim

WORKDIR /app

COPY api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY api/ .
COPY saved_models/ saved_models/

EXPOSE 5000

CMD ["python", "app.py"]
